version: '3'

services:
  web-dev:
    container_name: web-dev
    build:
      context: .
      dockerfile: ./docker/dev/web/Dockerfile
    env_file:
      - ./docker/dev/web/.env
      - ./docker/dev/db/.env
    ports:
      - '3012:3012'
    volumes:
      - ./src/frontend:/app
    restart: always
    # networks:
    #   - default

# networks:
#   default:
#     external: true
#     name: v2.0_network