services:
  with-docker-multi-env-production:
    build:
      context: ../../../
      dockerfile: docker/prod/web/Dockerfile
    image: with-docker-multi-env-production
    ports:
      - "3012:3012"
